# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExchangeUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(500, 274)
        Form.setMinimumSize(QtCore.QSize(356, 261))
        Form.setSizeIncrement(QtCore.QSize(356, 261))
        Form.setBaseSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setFocusPolicy(QtCore.Qt.ClickFocus)
        Form.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        Form.setAcceptDrops(True)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setAutoFillBackground(True)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(200, 170, 75, 23))
        self.pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 60, 321, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(24)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.labelA = QtWidgets.QLabel(self.layoutWidget)
        self.labelA.setObjectName("labelA")
        self.gridLayout.addWidget(self.labelA, 1, 0, 1, 1)
        self.labelB = QtWidgets.QLabel(self.layoutWidget)
        self.labelB.setObjectName("labelB")
        self.gridLayout.addWidget(self.labelB, 1, 1, 1, 1)
        self.labelC = QtWidgets.QLabel(self.layoutWidget)
        self.labelC.setObjectName("labelC")
        self.gridLayout.addWidget(self.labelC, 1, 2, 1, 1)
        self.labelD = QtWidgets.QLabel(self.layoutWidget)
        self.labelD.setObjectName("labelD")
        self.gridLayout.addWidget(self.labelD, 1, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Refresh"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">即期買匯</p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">現金買匯</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">即期賣匯</p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\">現今賣匯</p></body></html>"))
        self.labelA.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.labelB.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.labelC.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.labelD.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
