# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExchangeUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NZDtoTWD(object):
    def setupUi(self, NZDtoTWD):
        NZDtoTWD.setObjectName("NZDtoTWD")
        NZDtoTWD.setWindowModality(QtCore.Qt.NonModal)
        NZDtoTWD.resize(500, 274)
        NZDtoTWD.setMinimumSize(QtCore.QSize(356, 261))
        NZDtoTWD.setSizeIncrement(QtCore.QSize(356, 261))
        NZDtoTWD.setBaseSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        NZDtoTWD.setFont(font)
        NZDtoTWD.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        NZDtoTWD.setFocusPolicy(QtCore.Qt.ClickFocus)
        NZDtoTWD.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        NZDtoTWD.setAcceptDrops(True)
        NZDtoTWD.setLayoutDirection(QtCore.Qt.LeftToRight)
        NZDtoTWD.setAutoFillBackground(True)
        self.pushButton = QtWidgets.QPushButton(NZDtoTWD)
        self.pushButton.setGeometry(QtCore.QRect(220, 170, 75, 23))
        self.pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(NZDtoTWD)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 60, 321, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(24)
        self.gridLayout.setObjectName("gridLayout")
        self.labelD = QtWidgets.QLabel(self.layoutWidget)
        self.labelD.setObjectName("labelD")
        self.gridLayout.addWidget(self.labelD, 1, 3, 1, 1)
        self.labelB = QtWidgets.QLabel(self.layoutWidget)
        self.labelB.setObjectName("labelB")
        self.gridLayout.addWidget(self.labelB, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.labelA = QtWidgets.QLabel(self.layoutWidget)
        self.labelA.setObjectName("labelA")
        self.gridLayout.addWidget(self.labelA, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.labelC = QtWidgets.QLabel(self.layoutWidget)
        self.labelC.setObjectName("labelC")
        self.gridLayout.addWidget(self.labelC, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(NZDtoTWD)
        QtCore.QMetaObject.connectSlotsByName(NZDtoTWD)

    def retranslateUi(self, NZDtoTWD):
        _translate = QtCore.QCoreApplication.translate
        NZDtoTWD.setWindowTitle(_translate("NZDtoTWD", "NZDtoTWD"))
        self.pushButton.setText(_translate("NZDtoTWD", "Refresh"))
        self.labelD.setText(_translate("NZDtoTWD", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.labelB.setText(_translate("NZDtoTWD", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("NZDtoTWD", "<html><head/><body><p align=\"center\">即期賣匯</p></body></html>"))
        self.label_2.setText(_translate("NZDtoTWD", "<html><head/><body><p align=\"center\">現金買匯</p></body></html>"))
        self.labelA.setText(_translate("NZDtoTWD", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("NZDtoTWD", "<html><head/><body><p align=\"center\">現金賣匯</p></body></html>"))
        self.labelC.setText(_translate("NZDtoTWD", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("NZDtoTWD", "<html><head/><body><p align=\"center\">即期買匯</p></body></html>"))
